name: Daily update
# fix by manh mit

on:
  schedule:
    - cron: "0 9 * * 1-5" # 09:00 on every day-of-week from Monday through Friday.
    - cron: "0 13 * * 1-5" # At 13:00 on every day-of-week from Monday through Friday.
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get today price
        run: python get_price.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto update data" -a
      - name: Send message to Telegram channel
        run: python channel.py
